// BTstack - version.h
// - generated by ../src/get_version.sh
// - at 2014-07-13_17:22:06
#define BTSTACK_MAJOR 0
#define BTSTACK_MINOR 8
#define BTSTACK_REVISION 2692
#define BTSTACK_VERSION "0.8-2692"
#define BTSTACK_DATE "2014-07-13_17:22:06"